# Generated by Django 4.0.5 on 2022-06-07 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_rroduct_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rroduct',
            new_name='Product',
        ),
    ]
